export const rankingData = [
  {
    id: 1,
    rankNumber: 1,
    playerName: 'Marcos Burgos',
    lastTournamentPoints: 3,
    points: 56,
    matchPoints: 114,
    matchRecordsWin: 35,
    matchRecordsLose: 7,
    matchRecordsDraw: 7,
    gamesNumber: 49,
    winRate: 77.78,
  },
  {
    id: 2,
    rankNumber: 2,
    playerName: 'Carlos Jiménez',
    lastTournamentPoints: 0,
    points: 40,
    matchPoints: 100,
    matchRecordsWin: 31,
    matchRecordsLose: 9,
    matchRecordsDraw: 7,
    gamesNumber: 47,
    winRate: 68.25,
  },
  {
    id: 3,
    rankNumber: 3,
    playerName: 'Eddy Fidel',
    lastTournamentPoints: 0,
    points: 24,
    matchPoints: 58,
    matchRecordsWin: 17,
    matchRecordsLose: 6,
    matchRecordsDraw: 7,
    gamesNumber: 30,
    winRate: 53.85,
  },
  {
    id: 4,
    rankNumber: 4,
    playerName: 'Juan Batista',
    lastTournamentPoints: 0,
    points: 23,
    matchPoints: 52,
    matchRecordsWin: 15,
    matchRecordsLose: 16,
    matchRecordsDraw: 7,
    gamesNumber: 38,
    winRate: 43.86,
  },
  {
    id: 5,
    rankNumber: 5,
    playerName: 'Jorge Curiel',
    lastTournamentPoints: 1,
    points: 22,
    matchPoints: 53,
    matchRecordsWin: 15,
    matchRecordsLose: 15,
    matchRecordsDraw: 8,
    gamesNumber: 38,
    winRate: 51.52,
  },
  {
    id: 6,
    rankNumber: 6,
    playerName: 'Víctor Cordero',
    lastTournamentPoints: 2,
    points: 18,
    matchPoints: 43,
    matchRecordsWin: 12,
    matchRecordsLose: 15,
    matchRecordsDraw: 7,
    gamesNumber: 34,
    winRate: 0.0,
  },
  {
    id: 7,
    rankNumber: 7,
    playerName: 'Gabriel Uribe',
    lastTournamentPoints: 0,
    points: 18,
    matchPoints: 41,
    matchRecordsWin: 10,
    matchRecordsLose: 17,
    matchRecordsDraw: 4,
    gamesNumber: 31,
    winRate: 36.36,
  },
  {
    id: 8,
    rankNumber: 8,
    playerName: 'Pedro Pérez',
    lastTournamentPoints: 1,
    points: 17,
    matchPoints: 36,
    matchRecordsWin: 12,
    matchRecordsLose: 15,
    matchRecordsDraw: 0,
    gamesNumber: 27,
    winRate: 0.0,
  },
  {
    id: 9,
    rankNumber: 9,
    playerName: 'Carlos Corniel',
    lastTournamentPoints: 0,
    points: 16,
    matchPoints: 29,
    matchRecordsWin: 8,
    matchRecordsLose: 14,
    matchRecordsDraw: 6,
    gamesNumber: 28,
    winRate: 48.72,
  },
  {
    id: 10,
    rankNumber: 10,
    playerName: 'Luís Miranda',
    lastTournamentPoints: 0,
    points: 13,
    matchPoints: 29,
    matchRecordsWin: 9,
    matchRecordsLose: 8,
    matchRecordsDraw: 2,
    gamesNumber: 19,
    winRate: 0.0,
  },
  {
    id: 11,
    rankNumber: 11,
    playerName: 'Persio Bisonó',
    lastTournamentPoints: 0,
    points: 11,
    matchPoints: 34,
    matchRecordsWin: 11,
    matchRecordsLose: 2,
    matchRecordsDraw: 1,
    gamesNumber: 14,
    winRate: 0.0,
  },
  {
    id: 12,
    rankNumber: 12,
    playerName: 'Daniel Chan',
    lastTournamentPoints: 0,
    points: 10,
    matchPoints: 27,
    matchRecordsWin: 8,
    matchRecordsLose: 9,
    matchRecordsDraw: 8,
    gamesNumber: 25,
    winRate: 0.0,
  },
  {
    id: 13,
    rankNumber: 13,
    playerName: 'Harold Méndez',
    lastTournamentPoints: 0,
    points: 9,
    matchPoints: 27,
    matchRecordsWin: 7,
    matchRecordsLose: 7,
    matchRecordsDraw: 3,
    gamesNumber: 17,
    winRate: 0.0,
  },
  {
    id: 14,
    rankNumber: 14,
    playerName: 'Luís Rossi',
    lastTournamentPoints: 0,
    points: 9,
    matchPoints: 16,
    matchRecordsWin: 5,
    matchRecordsLose: 11,
    matchRecordsDraw: 1,
    gamesNumber: 17,
    winRate: 36.36,
  },
  {
    id: 15,
    rankNumber: 15,
    playerName: 'Gabriel Gómez',
    lastTournamentPoints: 0,
    points: 7,
    matchPoints: 21,
    matchRecordsWin: 7,
    matchRecordsLose: 4,
    matchRecordsDraw: 0,
    gamesNumber: 11,
    winRate: 0.0,
  },
  {
    id: 16,
    rankNumber: 16,
    playerName: 'Juan Julio Fuentes',
    lastTournamentPoints: 0,
    points: 6,
    matchPoints: 13,
    matchRecordsWin: 4,
    matchRecordsLose: 8,
    matchRecordsDraw: 1,
    gamesNumber: 13,
    winRate: 0.0,
  },
  {
    id: 17,
    rankNumber: 17,
    playerName: 'José Pastoriza',
    lastTournamentPoints: 0,
    points: 6,
    matchPoints: 7,
    matchRecordsWin: 2,
    matchRecordsLose: 2,
    matchRecordsDraw: 1,
    gamesNumber: 5,
    winRate: 0.0,
  },
  {
    id: 18,
    rankNumber: 18,
    playerName: 'Jorge Rosario',
    lastTournamentPoints: 0,
    points: 6,
    matchPoints: 7,
    matchRecordsWin: 2,
    matchRecordsLose: 7,
    matchRecordsDraw: 2,
    gamesNumber: 11,
    winRate: 0.0,
  },
  {
    id: 19,
    rankNumber: 19,
    playerName: 'María José Pantaleón',
    lastTournamentPoints: 0,
    points: 6,
    matchPoints: 6,
    matchRecordsWin: 1,
    matchRecordsLose: 8,
    matchRecordsDraw: 3,
    gamesNumber: 12,
    winRate: 0.0,
  },
  {
    id: 20,
    rankNumber: 20,
    playerName: 'Daniel Pastoriza',
    lastTournamentPoints: 0,
    points: 5,
    matchPoints: 11,
    matchRecordsWin: 3,
    matchRecordsLose: 9,
    matchRecordsDraw: 2,
    gamesNumber: 14,
    winRate: 0.0,
  },
  {
    id: 21,
    rankNumber: 21,
    playerName: 'Jumil Ortíz',
    lastTournamentPoints: 0,
    points: 4,
    matchPoints: 20,
    matchRecordsWin: 6,
    matchRecordsLose: 8,
    matchRecordsDraw: 2,
    gamesNumber: 16,
    winRate: 0.0,
  },
  {
    id: 22,
    rankNumber: 22,
    playerName: 'Juan Gil',
    lastTournamentPoints: 0,
    points: 4,
    matchPoints: 15,
    matchRecordsWin: 5,
    matchRecordsLose: 6,
    matchRecordsDraw: 0,
    gamesNumber: 11,
    winRate: 0.0,
  },
  {
    id: 23,
    rankNumber: 23,
    playerName: 'Luís Rodríguez',
    lastTournamentPoints: 0,
    points: 4,
    matchPoints: 10,
    matchRecordsWin: 3,
    matchRecordsLose: 4,
    matchRecordsDraw: 1,
    gamesNumber: 8,
    winRate: 0.0,
  },
  {
    id: 24,
    rankNumber: 24,
    playerName: 'Thomás Moisés',
    lastTournamentPoints: 0,
    points: 4,
    matchPoints: 10,
    matchRecordsWin: 3,
    matchRecordsLose: 0,
    matchRecordsDraw: 1,
    gamesNumber: 4,
    winRate: 0.0,
  },
  {
    id: 25,
    rankNumber: 25,
    playerName: 'René Brito',
    lastTournamentPoints: 0,
    points: 4,
    matchPoints: 6,
    matchRecordsWin: 2,
    matchRecordsLose: 2,
    matchRecordsDraw: 0,
    gamesNumber: 4,
    winRate: 0.0,
  },
  {
    id: 26,
    rankNumber: 26,
    playerName: 'Jesuth Núñez',
    lastTournamentPoints: 0,
    points: 4,
    matchPoints: 0,
    matchRecordsWin: 0,
    matchRecordsLose: 2,
    matchRecordsDraw: 0,
    gamesNumber: 2,
    winRate: 0.0,
  },
  {
    id: 27,
    rankNumber: 27,
    playerName: 'Jassam Mejía',
    lastTournamentPoints: 0,
    points: 2,
    matchPoints: 6,
    matchRecordsWin: 2,
    matchRecordsLose: 1,
    matchRecordsDraw: 0,
    gamesNumber: 3,
    winRate: 0.0,
  },
  {
    id: 28,
    rankNumber: 28,
    playerName: 'Luigi Jáquez',
    lastTournamentPoints: 0,
    points: 2,
    matchPoints: 6,
    matchRecordsWin: 2,
    matchRecordsLose: 1,
    matchRecordsDraw: 0,
    gamesNumber: 3,
    winRate: 0.0,
  },
  {
    id: 29,
    rankNumber: 29,
    playerName: 'Luís Correa',
    lastTournamentPoints: 0,
    points: 2,
    matchPoints: 3,
    matchRecordsWin: 1,
    matchRecordsLose: 5,
    matchRecordsDraw: 0,
    gamesNumber: 6,
    winRate: 0.0,
  },
  {
    id: 30,
    rankNumber: 30,
    playerName: 'Enmanuel González',
    lastTournamentPoints: 0,
    points: 1,
    matchPoints: 6,
    matchRecordsWin: 2,
    matchRecordsLose: 2,
    matchRecordsDraw: 0,
    gamesNumber: 4,
    winRate: 0.0,
  },
  {
    id: 31,
    rankNumber: 31,
    playerName: 'Manuel Mañon',
    lastTournamentPoints: 0,
    points: 1,
    matchPoints: 5,
    matchRecordsWin: 1,
    matchRecordsLose: 1,
    matchRecordsDraw: 2,
    gamesNumber: 4,
    winRate: 0.0,
  },
  {
    id: 32,
    rankNumber: 32,
    playerName: 'Maguá Moquete',
    lastTournamentPoints: 0,
    points: 1,
    matchPoints: 3,
    matchRecordsWin: 1,
    matchRecordsLose: 2,
    matchRecordsDraw: 0,
    gamesNumber: 3,
    winRate: 0.0,
  },
  {
    id: 33,
    rankNumber: 33,
    playerName: 'Esteban García',
    lastTournamentPoints: 0,
    points: 1,
    matchPoints: 3,
    matchRecordsWin: 1,
    matchRecordsLose: 3,
    matchRecordsDraw: 0,
    gamesNumber: 4,
    winRate: 0.0,
  },
  {
    id: 34,
    rankNumber: 34,
    playerName: 'Juan C.',
    lastTournamentPoints: 0,
    points: 1,
    matchPoints: 3,
    matchRecordsWin: 1,
    matchRecordsLose: 2,
    matchRecordsDraw: 0,
    gamesNumber: 3,
    winRate: 0.0,
  },
  {
    id: 35,
    rankNumber: 35,
    playerName: 'Gabriele Santana',
    lastTournamentPoints: 0,
    points: 1,
    matchPoints: 1,
    matchRecordsWin: 0,
    matchRecordsLose: 1,
    matchRecordsDraw: 1,
    gamesNumber: 2,
    winRate: 0.0,
  },
];
